pipeline {
  agent none
  stages {
    stage('DB') {
      agent {
        docker { image 'mcr.microsoft.com/mssql/server:2022-latest' }
      }
      steps {
        print "Hello World"
      }
    }
  }
}
