pipeline {
  agent none
    stage('DB') {
      agent {
        docker { image 'mssql:latest' }
      }
      steps {
        SELECT @@SERVERNAME,
       SERVERPROPERTY('ComputerNamePhysicalNetBIOS'),
       SERVERPROPERTY('MachineName'),
       SERVERPROPERTY('ServerName');
      }
    }
  }
}
